[general]
debug     = false
guild     = "GUILD ID HERE"

[bot]
token  = "TOKEN SECRET HERE"
prefix = "!"

[user]
email    = "EMAIL HERE"
password = "PASSWORD HERE"
token    = "TOKEN HERE - OBTAIN WITH 'starbot-forwarder get-token email password'"

[email]
domain   = "smtp.gmail.com"
port     = 587
address  = "example@gmail.com"
password = "some important password"

[database]
file = "database.db"

[triggers]
address  = ":7827"
password = "RANDOM STRING HERE"

[roles]
verified  = "ROLE ID HERE"
moderator = "ROLE ID HERE"
onAir     = "ROLE ID HERE"
support   = "ROLE ID HERE"

[channels]
studio      = "CHANNEL ID HERE"
controlRoom = "CHANNEL ID HERE"

[autoplay]
announce     = "As there's nobody in the studio at the moment, I'm going to start autoplay."
slotUp       = "As the hour is over and there's no upcoming show, I'm going to start autoplay."
commands     = [ "LIST", " COMMANDS", "HERE" ]
ignoredUsers = [ "FORWARDER BOT HERE", "MUSIC BOT HERE" ]

[verification]
userUnverified     = "The email address has been freed and the user who was registered with that email has been unverified."
emailNotFound      = "I couldn't find a user with that email address."
invalidEmail       = "Sorry, that email isn't a valid show host's email address."
takenEmail         = "Sorry, that email has already been taken by %s."
emailSent          = "You have been sent an email containing a verification code. Please enter `%sconfirm` followed by the code within 15 minutes."
emailSubject       = "Starbot Verification Code"
emailContentsFile  = "someotherfile.html"
allowedEmailsFile  = "somefile.txt"
confirmationFailed = "Sorry, I couldn't match that confirmation code to any stored for your account."
confirmed          = "Your email address has been confirmed and you are now verified."

[msg]
syntaxError           = "Incorrect syntax: "
invalidTime           = "The time provided was incorrect. Please use a format like Monday 3PM."
inviteInvited         = "<@%s> has been invited to the studio."
registerNewShow       = "<@%s> has been registered as the key show host for *%s* on %s at %s."
registerReplaced      = "<@%s> has been registered as the key show host for *%s* on %s at %s, replacing *%s* which was hosted by %s."
registerWrongRole     = "Sorry, that user doesn't have the correct role to host a show."
showNoShowFound       = "There is no show registered at that time."
showShowFound         = "The show on %s at %s is called *%s* and the show is hosted by %s."
showsembedSet         = "The shows embed has been created in <#%s>."
showsembedReplaced    = "The shows embed has been moved to <#%s>. The old embed will not be updated and will need to be manually deleted."
uninviteUninvited     = "<@%s> has been booted out of the studio."
unregisterNoShowFound = "There is no show registered at that time."
unregisterShowDeleted = "The show on %s at %s has been unregistered."

[misc]
listenersUrl = "http://example.com/current_listeners.php"
