[general]
debug     = false
guild     = "GUILD ID HERE"

[bot]
token  = "TOKEN SECRET HERE"
prefix = "!"

[user]
email    = "EMAIL HERE"
password = "PASSWORD HERE"
token    = "TOKEN HERE - OBTAIN WITH 'starbot-forwarder get-token email password'"

[database]
file = "database.db"

[roles]
moderator = "ROLE ID HERE"
onAir     = "ROLE ID HERE"

[channels]
studio      = "CHANNEL ID HERE"
controlRoom = "CHANNEL ID HERE"

[autoplay]
announce     = "As there's nobody in the studio at the moment, I'm going to start autoplay."
commands     = [ "LIST", " COMMANDS", "HERE" ]
ignoredUsers = [ "FORWARDER BOT HERE", "MUSIC BOT HERE" ]

[msg]
syntaxError           = "Incorrect syntax: "
invalidTime           = "The time provided was incorrect. Please use a format like Monday 3PM."
inviteInvited         = "<@%s> has been invited to the studio."
registerNewShow       = "<@%s> has been registered as the key show host for *%s* on %s at %s."
registerReplaced      = "<@%s> has been registered as the key show host for *%s* on %s at %s, replacing <@%s> who hosted *%s*."
showNoShowFound       = "There is no show registered at that time."
showShowFound         = "The show on %s at %s is called *%s* and the key show host is <@%s>."
showsembedSet         = "The shows embed has been created in <#%s>."
showsembedReplaced    = "The shows embed has been moved to <#%s>. The old embed will not be updated and will need to be manually deleted."
uninviteUninvited     = "<@%s> has been booted out of the studio."
unregisterNoShowFound = "There is no show registered at that time."
unregisterShowDeleted = "The show on %s at %s has been unregistered."

[testing]
quickerJobs = false
